name: spark ci/cd pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
    build-and-run:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Set up JDK 11
          uses: actions/setup-java@v2
          with:
            distribution: 'temurin'
            java-version: '11'


        
          
        
        - name: set up docker
          run: docker --version

        - name: Build docker image
          run: docker build -t spark-local -f docker/Dockerfile .

        - name: Run Spark job
          run: |
            docker run --rm -v ${{ github.workspace }}/output:/app/output spark-local

        - name: Upload output files
          uses: actions/upload-artifact@v4
          with:
             name: spark-output
             path: output/
